language: csharp
solution: TravisTest.sln
install:
  - nuget restore TravisTest.sln
  - nuget install NUnit.Runners -Version 3.6.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release TravisTest.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe ./TravisTest.UT/bin/Release/TravisTest.UT.dll
after_success:
  -  Write-Host "Hello World"